FROM node:12.14.0
 
RUN apt-get update && apt-get install -y python git cmake python-pip build-essential
RUN pip install mbed-cli click requests
RUN pip install colorama PySerial PrettyTable Jinja2 IntelHex junit-xml pyYAML requests mbed-ls mbed-host-tests mbed-greentea beautifulsoup4 fuzzywuzzy pyelftools jsonschema future
